"""Architecture graph endpoints.

Backs the Settings → Architecture sub-page in the web UI. The data is
generated by ``scripts/gen_architecture.py`` (AST-parsed imports, no
guesses) and cached in ``plans/architecture_data.json``.

GET  /api/architecture            — return current cached graph JSON
POST /api/architecture/regenerate — re-run the generator script
"""
from __future__ import annotations

import json
import logging
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict

from fastapi import APIRouter, HTTPException

logger = logging.getLogger(__name__)

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_DATA_PATH = _REPO_ROOT / "plans" / "architecture_data.json"
_GENERATOR = _REPO_ROOT / "scripts" / "gen_architecture.py"

_REGEN_TIMEOUT_S = 120


def build_architecture_router() -> APIRouter:
    router = APIRouter(prefix="/api/architecture", tags=["architecture"])

    @router.get("")
    def get_architecture() -> Dict[str, Any]:
        if not _DATA_PATH.exists():
            raise HTTPException(
                404,
                f"architecture_data.json not found at {_DATA_PATH}; "
                "POST /api/architecture/regenerate to create it",
            )
        try:
            data = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise HTTPException(500, f"corrupt architecture_data.json: {exc}")
        st = _DATA_PATH.stat()
        return {
            "modules": data.get("modules", []),
            "edges": data.get("edges", []),
            "generated_at": st.st_mtime,
            "size_bytes": st.st_size,
        }

    @router.post("/regenerate")
    def regenerate_architecture() -> Dict[str, Any]:
        if not _GENERATOR.exists():
            raise HTTPException(500, f"generator missing: {_GENERATOR}")
        t0 = time.monotonic()
        # --json flag writes the JSON sidecar; the HTML is also rewritten
        # but we don't surface it (the React UI renders from JSON).
        try:
            proc = subprocess.run(
                [sys.executable, str(_GENERATOR)],
                cwd=str(_REPO_ROOT),
                capture_output=True,
                text=True,
                timeout=_REGEN_TIMEOUT_S,
            )
        except subprocess.TimeoutExpired:
            raise HTTPException(504, f"generator timed out after {_REGEN_TIMEOUT_S}s")
        duration_ms = int((time.monotonic() - t0) * 1000)
        if proc.returncode != 0:
            logger.warning("gen_architecture failed rc=%s stderr=%s",
                           proc.returncode, proc.stderr[:500])
            raise HTTPException(
                500,
                f"generator failed (rc={proc.returncode}): {proc.stderr.strip()[:300]}",
            )
        return {
            "ok": True,
            "duration_ms": duration_ms,
            "stdout_tail": proc.stdout.strip().splitlines()[-5:] if proc.stdout else [],
        }

    return router
