"""
Fleet session — the in-CLI runtime state holder for an active fleet.

One FleetSession is created when the user runs ``/fleet start <project>``
from inside a NeoMind CLI session. It wraps a ``FleetLauncher``, holds
per-member event ring buffers (for the focus-view renderer), tracks
which member is currently focused, and provides the thin dispatch
helpers the CLI command layer calls when the user types input.

Design principles (from 2026-04-12 user directive):

1. **Leader = main session** — the fleet's leader role is the user's
   current CLI session. We do NOT spawn a separate leader process.
   The sub-agents are all non-leader members of the project.yaml.
2. **One terminal interface, focus-switchable** — the session tracks
   a ``focus`` slot that is either ``"leader"`` (= main persona view)
   or a sub-agent member name. Input + output rendering is routed by
   that slot. No tmux-style panes, no separate windows.
3. **Per-agent isolation** — each sub-agent has its own event ring
   buffer and its own input history. Switching focus does not leak
   one agent's context into another.
4. **Persona-agnostic** — this module contains zero persona string
   literals (grep audit on commit). It works for any registered
   persona without modification.

Contract: plans/2026-04-12_phase4_fleet_llm_loop.md §11 (Phase 5
scope expansion).
"""

from __future__ import annotations

import asyncio
import logging
import re
import time
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Deque, Dict, List, Optional

from agent.agentic.swarm import format_task_notification
from fleet.launch_project import FleetLauncher
from fleet.project_schema import MemberConfig, ProjectConfig, load_project_config

logger = logging.getLogger(__name__)

__all__ = [
    "FleetEvent",
    "FleetSession",
    "FleetSessionError",
    "LEADER_FOCUS",
    "parse_mention",
]


LEADER_FOCUS = "__leader__"
"""Sentinel focus value meaning 'main session / leader view'."""


# Event buffer size per member — bounds memory at ~200 small dicts ≈ 50 KB
_EVENT_BUFFER_CAP = 200

# Regex for inline @mention dispatch from leader view
# Matches `@name ` or `@name\n` at the start of a message
# name pattern matches the project_schema member name validation
_MENTION_RE = re.compile(r"^@([a-zA-Z][a-zA-Z0-9_-]*)\s+(.*)", re.DOTALL)


class FleetSessionError(RuntimeError):
    """Raised on FleetSession misuse (no active fleet, unknown member,
    can't start, etc.). The CLI layer catches and surfaces these as
    friendly error messages."""


@dataclass
class FleetEvent:
    """One observable event in a member's activity stream.

    Kept deliberately small so 200-entry ring buffers stay under 50 KB
    per member. Events are generated by ``fleet.worker_turn`` via the
    ``event_sink`` callback (Phase 5.2) and by the session itself for
    user-originated actions (submit, mention dispatch, focus change).
    """

    ts: float
    member: str
    kind: str        # "task_claimed", "llm_call_start", "llm_call_end",
                     # "task_completed", "task_failed", "user_message",
                     # "system", ...
    content: str     # short display text (preview, error, system note)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def render(self) -> str:
        """Compact one-line display for the focus-view printer."""
        t = time.strftime("%H:%M:%S", time.localtime(self.ts))
        return f"[{t}] {self.kind}: {self.content}"


def parse_mention(text: str) -> Optional[tuple]:
    """Parse an `@member-name rest of message` string.

    Returns ``(name, rest)`` if the input starts with a valid @mention,
    None otherwise. Member name validation mirrors
    ``project_schema.MEMBER_NAME_RE`` (letter-start, alnum / _ / -).

    Examples:
        >>> parse_mention("@fin-rt analyze AAPL")
        ('fin-rt', 'analyze AAPL')
        >>> parse_mention("hello world")    # no mention
        >>> parse_mention("@ missing name")  # invalid
    """
    if not isinstance(text, str):
        return None
    m = _MENTION_RE.match(text.strip())
    if not m:
        return None
    return m.group(1), m.group(2).strip()


class FleetSession:
    """Runtime holder for an active fleet inside a CLI session.

    The CLI's NeoMindInterface creates one of these on ``/fleet start``,
    stores it at ``self._fleet_session``, and tears it down on
    ``/fleet stop``. All fleet-related UI state lives here, so the CLI
    can check ``session is not None`` as the "fleet active?" predicate.
    """

    def __init__(
        self,
        config: ProjectConfig,
        *,
        base_dir: Optional[str] = None,
        shared_memory: Optional[Any] = None,
    ):
        self.config = config
        self._base_dir = base_dir
        self._shared_memory = shared_memory

        # Event ring buffers — one per member, capped to avoid memory growth
        self._event_buffers: Dict[str, Deque[FleetEvent]] = {
            m.name: deque(maxlen=_EVENT_BUFFER_CAP)
            for m in config.members
        }

        # Per-member input history (strings the user typed while focused
        # on that member). CLI can render a mini "recent commands" view.
        self._input_histories: Dict[str, List[str]] = {
            m.name: [] for m in config.members
        }

        # Focus state — starts at leader (= normal main session view)
        self._focus: str = LEADER_FOCUS

        # The underlying launcher. Created on start(), None before.
        self._launcher: Optional[FleetLauncher] = None
        self._start_time: Optional[float] = None

    # ── Lifecycle ──────────────────────────────────────────────────

    async def start(self) -> None:
        """Spawn the underlying FleetLauncher. Idempotent: subsequent
        calls warn and return."""
        if self._launcher is not None:
            logger.warning("FleetSession.start: already running")
            return
        self._launcher = FleetLauncher(
            self.config,
            base_dir=self._base_dir,
            shared_memory=self._shared_memory,
            event_sink=self._record_event,
        )
        await self._launcher.start()
        self._start_time = time.time()
        # Seed each member with a "spawned" event for the focus view
        now = time.time()
        for m in self.config.members:
            self._event_buffers[m.name].append(FleetEvent(
                ts=now,
                member=m.name,
                kind="spawned",
                content=f"persona={m.persona} role={m.role}",
            ))

    async def stop(self, timeout: float = 30.0) -> None:
        """Gracefully stop the launcher. Idempotent."""
        if self._launcher is None:
            return
        try:
            await self._launcher.stop(timeout=timeout)
        finally:
            self._launcher = None

    @property
    def running(self) -> bool:
        return self._launcher is not None

    @property
    def project_id(self) -> str:
        return self.config.project_id

    @property
    def uptime(self) -> float:
        if self._start_time is None:
            return 0.0
        return time.time() - self._start_time

    # ── Member introspection ───────────────────────────────────────

    def member_names(self) -> List[str]:
        """Non-leader members, in project.yaml order — the tags that
        appear in the status bar. Leader is represented separately as
        the ``[main]`` / ``[persona]`` slot by the CLI."""
        return [m.name for m in self.config.members if m.role != "leader"]

    def all_member_names(self) -> List[str]:
        """Every member including the leader, in project.yaml order."""
        return [m.name for m in self.config.members]

    def get_member(self, name: str) -> Optional[MemberConfig]:
        for m in self.config.members:
            if m.name == name:
                return m
        return None

    # ── Focus ──────────────────────────────────────────────────────

    @property
    def focus(self) -> str:
        """Current focus — ``LEADER_FOCUS`` or a member name."""
        return self._focus

    def is_focused_on_leader(self) -> bool:
        return self._focus == LEADER_FOCUS

    def focused_member_name(self) -> Optional[str]:
        return None if self._focus == LEADER_FOCUS else self._focus

    def set_focus(self, target: str) -> bool:
        """Set focus to a specific target. ``target`` must be either
        ``LEADER_FOCUS`` or a valid non-leader member name. Returns
        True if the focus changed, False if it was already there or
        invalid."""
        if target == LEADER_FOCUS:
            if self._focus == LEADER_FOCUS:
                return False
            self._focus = LEADER_FOCUS
            return True
        if self.get_member(target) is None or target not in self.member_names():
            return False
        if self._focus == target:
            return False
        self._focus = target
        return True

    def cycle_focus(self, direction: int = 1) -> str:
        """Move focus one step forward (+1) or backward (-1) through
        the sequence ``[LEADER_FOCUS] + member_names()``. Wraps around.

        Returns the new focus value.
        """
        sequence = [LEADER_FOCUS] + self.member_names()
        try:
            idx = sequence.index(self._focus)
        except ValueError:
            idx = 0
        new_idx = (idx + direction) % len(sequence)
        self._focus = sequence[new_idx]
        return self._focus

    # ── Event recording ────────────────────────────────────────────

    def _record_event(self, member: str, event_data: Dict[str, Any]) -> None:
        """Callback passed to FleetLauncher as event_sink. Workers call
        it via worker_turn when interesting things happen. Synchronous
        and fast — appends to an in-memory deque."""
        if member not in self._event_buffers:
            logger.debug("event for unknown member %s, dropping", member)
            return
        event = FleetEvent(
            ts=time.time(),
            member=member,
            kind=str(event_data.get("kind", "event")),
            content=str(event_data.get("content", ""))[:500],
            metadata={
                k: v for k, v in event_data.items()
                if k not in ("kind", "content")
            },
        )
        self._event_buffers[member].append(event)

    def record_user_event(
        self, member: str, kind: str, content: str,
    ) -> None:
        """Public: CLI layer uses this to log user-originated events
        (submitted a task, switched focus, etc.) into the target
        member's ring buffer. Useful for the focus-view timeline."""
        if member == LEADER_FOCUS:
            return  # leader has no ring buffer — CLI owns its own history
        if member not in self._event_buffers:
            raise FleetSessionError(f"unknown member: {member!r}")
        self._event_buffers[member].append(FleetEvent(
            ts=time.time(),
            member=member,
            kind=kind,
            content=content,
        ))

    def recent_events(
        self, member: str, limit: int = 15,
    ) -> List[FleetEvent]:
        """Return the last ``limit`` events for a member, oldest-first."""
        if member == LEADER_FOCUS:
            return []
        buf = self._event_buffers.get(member)
        if buf is None:
            return []
        items = list(buf)
        return items[-limit:] if limit > 0 else items

    # ── Input history ──────────────────────────────────────────────

    def record_input(self, member: str, text: str) -> None:
        """Record a user-typed input while focused on ``member``.
        Caps at 50 entries per member to bound memory."""
        if member == LEADER_FOCUS or member not in self._input_histories:
            return
        hist = self._input_histories[member]
        hist.append(text)
        if len(hist) > 50:
            del hist[:-50]

    def input_history(self, member: str) -> List[str]:
        return list(self._input_histories.get(member, []))

    # ── Task dispatch ──────────────────────────────────────────────

    async def submit_to_member(
        self, member_name: str, task_description: str,
    ) -> str:
        """Dispatch a task to a specific member via the underlying
        supervisor. Raises FleetSessionError if fleet not running or
        member unknown."""
        if self._launcher is None or self._launcher._supervisor is None:
            raise FleetSessionError("fleet not running")
        if self.get_member(member_name) is None:
            raise FleetSessionError(f"unknown member: {member_name!r}")

        supervisor = self._launcher._supervisor
        task_id = supervisor.dispatch_task(
            description=task_description,
            target_member=member_name,
        )
        # Also record in the ring buffer so the focus view shows it
        self._event_buffers[member_name].append(FleetEvent(
            ts=time.time(),
            member=member_name,
            kind="task_received",
            content=task_description[:200],
            metadata={"task_id": task_id},
        ))
        return task_id

    async def submit_to_persona(
        self, persona: str, task_description: str,
    ) -> str:
        """Dispatch a task to the first idle worker with the given
        persona. Thin wrapper around supervisor.dispatch_task."""
        if self._launcher is None or self._launcher._supervisor is None:
            raise FleetSessionError("fleet not running")
        return self._launcher._supervisor.dispatch_task(
            description=task_description,
            target_persona=persona,
        )

    async def submit_to_queue(self, task_description: str) -> str:
        """Add a task to the shared queue for any idle worker to claim."""
        if self._launcher is None or self._launcher._supervisor is None:
            raise FleetSessionError("fleet not running")
        return self._launcher._supervisor.dispatch_task(task_description)

    # ── Status snapshot ────────────────────────────────────────────

    def status_snapshot(self) -> Dict[str, Any]:
        """Compact status dict used by the /fleet status command and
        the bottom toolbar rendering."""
        snapshot = {
            "project_id": self.config.project_id,
            "running": self.running,
            "uptime_s": self.uptime,
            "focus": self._focus,
            "members": [],
        }
        if self._launcher and self._launcher._supervisor:
            try:
                super_status = self._launcher._supervisor.get_team_status()
                snapshot["supervisor"] = super_status
            except Exception as exc:
                snapshot["supervisor_error"] = str(exc)
        for m in self.config.members:
            if m.role == "leader":
                continue
            buf_len = len(self._event_buffers[m.name])
            snapshot["members"].append({
                "name": m.name,
                "persona": m.persona,
                "role": m.role,
                "events": buf_len,
            })
        return snapshot

    # ── Leader/main session helper ─────────────────────────────────

    def handle_leader_input(
        self, text: str,
    ) -> Optional[tuple]:
        """Preprocess user input typed in the leader view.

        Returns:
            - None — nothing to dispatch; caller handles normally
            - (member_name, rest_of_text) — user typed @mention,
              caller should submit ``rest`` as a task to ``member``

        This enables the "from main session I can @fin-rt analyze AAPL"
        flow without requiring the user to focus-switch. If the
        mention references an unknown member, returns None and lets
        the text fall through to normal LLM handling so users aren't
        blocked by typos.
        """
        parsed = parse_mention(text)
        if parsed is None:
            return None
        name, rest = parsed
        if name not in self.member_names() or not rest:
            return None
        return name, rest
