"""
Example skill: Codebase documentation.

Provides knowledge about the current project's structure, patterns, and conventions.
"""

from typing import Optional
import os
import json

from ..base import Skill, SkillMetadata, SkillType, SkillLoadError


class CodebaseSkill(Skill):
    """Skill providing project-specific knowledge."""

    def __init__(self, project_root: Optional[str] = None, metadata: Optional[SkillMetadata] = None):
        self.project_root = project_root or os.getcwd()

        if metadata is None:
            metadata = SkillMetadata(
                name="codebase",
                description="Project-specific documentation, structure, and conventions",
                skill_type=SkillType.CODEBASE,
                tags=["project", "codebase", "structure", "conventions"],
                size_estimate=2000,
                cache_ttl=300,  # Short TTL since codebase may change
                dependencies=["python_api"],  # Depends on Python API
            )

        super().__init__(metadata)

    def _default_metadata(self) -> SkillMetadata:
        """Return default metadata."""
        return SkillMetadata(
            name="codebase",
            description="Project-specific documentation",
            skill_type=SkillType.CODEBASE,
            tags=["project", "codebase"],
            size_estimate=2000,
            cache_ttl=300,
            dependencies=[],
        )

    def load_content(self) -> str:
        """Load codebase documentation by analyzing project structure."""
        try:
            content_parts = []

            # Project overview
            content_parts.append(self._generate_project_overview())

            # Directory structure
            content_parts.append(self._analyze_directory_structure())

            # Configuration files
            content_parts.append(self._analyze_config_files())

            # Python-specific analysis
            content_parts.append(self._analyze_python_code())

            # Development workflow
            content_parts.append(self._document_workflow())

            return "\n".join(content_parts)

        except Exception as e:
            raise SkillLoadError(f"Failed to analyze codebase: {e}") from e

    def _generate_project_overview(self) -> str:
        """Generate project overview section."""
        project_name = os.path.basename(self.project_root)

        return f"""# Codebase Documentation: {project_name}

## Project Overview

**Root Directory**: `{self.project_root}`

This documentation is automatically generated by analyzing the project structure.
It provides insights into the project's organization, key files, and development patterns.
"""

    def _analyze_directory_structure(self) -> str:
        """Analyze and document directory structure."""
        dir_structure = []

        def scan_dir(path: str, indent: int = 0):
            try:
                entries = os.listdir(path)
                for entry in sorted(entries):
                    full_path = os.path.join(path, entry)
                    rel_path = os.path.relpath(full_path, self.project_root)

                    # Skip hidden directories and common ignore patterns
                    if entry.startswith('.') or entry in ['__pycache__', 'node_modules', '.git', '.venv', 'venv']:
                        continue

                    prefix = "  " * indent + "├── "
                    if os.path.isdir(full_path):
                        dir_structure.append(f"{prefix}{entry}/")
                        scan_dir(full_path, indent + 1)
                    else:
                        dir_structure.append(f"{prefix}{entry}")
            except (PermissionError, OSError):
                pass

        dir_structure.append("📁 Project Structure:")
        scan_dir(self.project_root)

        return "\n".join(dir_structure[:50])  # Limit to 50 entries

    def _analyze_config_files(self) -> str:
        """Analyze configuration files."""
        config_files = []
        common_configs = [
            'pyproject.toml', 'setup.py', 'requirements.txt', 'Pipfile',
            'package.json', 'docker-compose.yml', 'Dockerfile',
            '.gitignore', '.env.example', '.env', 'README.md',
            'Makefile', 'tox.ini', 'pytest.ini', 'setup.cfg',
            'MANIFEST.in', 'LICENSE', 'CONTRIBUTING.md',
        ]

        for config_file in common_configs:
            config_path = os.path.join(self.project_root, config_file)
            if os.path.exists(config_path):
                try:
                    size = os.path.getsize(config_path)
                    config_files.append(f"- `{config_file}` ({size} bytes)")

                    # Read and summarize key content for important files
                    if config_file in ['pyproject.toml', 'setup.py', 'requirements.txt', 'package.json']:
                        with open(config_path, 'r', encoding='utf-8') as f:
                            content = f.read(2000)  # Read first 2000 chars
                            lines = content.split('\n')[:10]
                            summary = '\\n  '.join(lines)
                            config_files.append(f"  Preview: {summary}")
                except Exception:
                    config_files.append(f"- `{config_file}` (exists)")

        if config_files:
            return "\n## Configuration Files\n" + "\n".join(config_files)
        return ""

    def _analyze_python_code(self) -> str:
        """Analyze Python code structure."""
        python_files = []

        for root, dirs, files in os.walk(self.project_root):
            # Skip hidden and virtual env directories
            dirs[:] = [d for d in dirs if not d.startswith('.') and d not in ['__pycache__', 'venv', '.venv', 'node_modules']]

            for file in files:
                if file.endswith('.py'):
                    rel_path = os.path.relpath(os.path.join(root, file), self.project_root)
                    python_files.append(f"- `{rel_path}`")

        if python_files:
            # Count packages and modules
            packages = sum(1 for f in python_files if '/__init__.py' in f)
            modules = len(python_files) - packages

            return f"""
## Python Code Analysis

**Statistics**:
- Total Python files: {len(python_files)}
- Packages (with __init__.py): {packages}
- Modules: {modules}

**Key Python Files**:
{chr(10).join(python_files[:20])}{'...' if len(python_files) > 20 else ''}
"""
        return ""

    def _document_workflow(self) -> str:
        """Document development workflow based on project artifacts."""
        workflow = []

        # Check for version control
        git_dir = os.path.join(self.project_root, '.git')
        if os.path.exists(git_dir):
            workflow.append("## Development Workflow")
            workflow.append("- **Version Control**: Git")

            # Check for common CI/CD files
            ci_files = ['.github/workflows', '.gitlab-ci.yml', 'azure-pipelines.yml', '.travis.yml']
            for ci_file in ci_files:
                ci_path = os.path.join(self.project_root, ci_file)
                if os.path.exists(ci_path):
                    workflow.append(f"- **CI/CD**: {ci_file}")
                    break

        # Check for testing framework
        test_dirs = ['tests', 'test', 'specs']
        test_files = ['pytest.ini', 'setup.cfg', 'tox.ini', '.coveragerc']

        for test_dir in test_dirs:
            test_path = os.path.join(self.project_root, test_dir)
            if os.path.exists(test_path):
                workflow.append("- **Testing**: Directory `{}` found".format(test_dir))
                break

        for test_file in test_files:
            test_path = os.path.join(self.project_root, test_file)
            if os.path.exists(test_path):
                workflow.append("- **Testing**: Config `{}` found".format(test_file))
                break

        # Check for documentation
        doc_dirs = ['docs', 'documentation']
        doc_files = ['README.md', 'CONTRIBUTING.md', 'CHANGELOG.md', 'CODE_OF_CONDUCT.md']

        for doc_dir in doc_dirs:
            doc_path = os.path.join(self.project_root, doc_dir)
            if os.path.exists(doc_path):
                workflow.append("- **Documentation**: Directory `{}` found".format(doc_dir))
                break

        for doc_file in doc_files:
            doc_path = os.path.join(self.project_root, doc_file)
            if os.path.exists(doc_path):
                workflow.append("- **Documentation**: File `{}` found".format(doc_file))
                break

        if workflow:
            return "\n".join(workflow)
        return ""

    def get_project_info(self) -> dict:
        """Get structured project information."""
        return {
            "project_root": self.project_root,
            "project_name": os.path.basename(self.project_root),
            "exists": os.path.exists(self.project_root),
        }


def create_codebase_skill(project_root: Optional[str] = None) -> CodebaseSkill:
    """Create and return a codebase skill instance."""
    return CodebaseSkill(project_root)