"""
Tools for NeoMind Agent.

Phase 2: Coding 完整功能
"""

# Re-export ToolRegistry and ToolResult for backward compatibility
# (many files import from agent.tools instead of agent.coding.tools)
from agent.coding.tools import ToolRegistry, ToolResult

from .semantic_search import SemanticSearchTool, SemanticResult
from .code_review import CodeReviewTool, ReviewResult, CodeIssue, IssueSeverity
from .agent_tool import AgentTool, AgentTask, AgentResult, AgentTaskStatus, spawn_agent
from .task_tools import TaskManager, Task, TaskResult, TaskStatus
from .lsp_tool import LSPTool, LSPAction, LSPLocation, LSPSymbol, LSPHoverInfo, LSPResult
from .git_tools import GitTools, GitResult
from .plan_mode import PlanModeManager, PlanModeResult
from .utility_tools import (
    WebFetchTool,
    WebFetchResult,
    WebSearchTool,
    WebSearchResult,
    SearchHit,
    NotebookEditTool,
    NotebookCell,
    NotebookResult,
    TodoWriteTool,
    TodoPriority,
    TodoItem,
    TodoResult,
    AskUserQuestionTool,
    AskResult,
    SleepTool,
    SleepResult,
    BriefTool,
    BriefResult,
)
from .advanced_tools import (
    REPLLanguage,
    WorktreeStatus,
    ConfigScope,
    WorktreeResult,
    REPLResult,
    MCPToolResult,
    SkillResult,
    ConfigResult,
    ToolSearchResult,
    TaskOutputResult,
    PowerShellResult,
    CronResult,
    WorktreeTool,
    REPLTool,
    MCPToolAdapter,
    ListMcpResourcesTool,
    ReadMcpResourceTool,
    SkillTool,
    ConfigTool,
    ToolSearchTool,
    TaskOutputTool,
    PowerShellTool,
    CronManager,
)
from .collaboration_tools import (
    SendMessageTool,
    ScheduleCronTool,
    RemoteTriggerTool,
    TeamManager,
    Message,
    MessageResult,
    MessageDirection,
    Schedule,
    ScheduleResult,
    Trigger,
    TriggerResult,
    TriggerMethod,
    Team,
    TeamMember,
    TeamResult,
    TeamRole,
)

__all__ = [
    'ToolRegistry',
    'ToolResult',
    'SemanticSearchTool',
    'SemanticResult',
    'CodeReviewTool',
    'ReviewResult',
    'CodeIssue',
    'IssueSeverity',
    'AgentTool',
    'AgentTask',
    'AgentResult',
    'AgentTaskStatus',
    'spawn_agent',
    'TaskManager',
    'Task',
    'TaskResult',
    'TaskStatus',
    'LSPTool',
    'LSPAction',
    'LSPLocation',
    'LSPSymbol',
    'LSPHoverInfo',
    'LSPResult',
    'GitTools',
    'GitResult',
    'PlanModeManager',
    'PlanModeResult',
    # Utility tools
    'WebFetchTool',
    'WebFetchResult',
    'WebSearchTool',
    'WebSearchResult',
    'SearchHit',
    'NotebookEditTool',
    'NotebookCell',
    'NotebookResult',
    'TodoWriteTool',
    'TodoPriority',
    'TodoItem',
    'TodoResult',
    'AskUserQuestionTool',
    'AskResult',
    'SleepTool',
    'SleepResult',
    'BriefTool',
    'BriefResult',
    # Advanced tools (Phase 2 - Claude CLI Parity)
    'REPLLanguage',
    'WorktreeStatus',
    'ConfigScope',
    'WorktreeResult',
    'REPLResult',
    'MCPToolResult',
    'SkillResult',
    'ConfigResult',
    'ToolSearchResult',
    'TaskOutputResult',
    'PowerShellResult',
    'CronResult',
    'WorktreeTool',
    'REPLTool',
    'MCPToolAdapter',
    'ListMcpResourcesTool',
    'ReadMcpResourceTool',
    'SkillTool',
    'ConfigTool',
    'ToolSearchTool',
    'TaskOutputTool',
    'PowerShellTool',
    'CronManager',
    # Collaboration & Scheduling
    'SendMessageTool',
    'ScheduleCronTool',
    'RemoteTriggerTool',
    'TeamManager',
    'Message',
    'MessageResult',
    'MessageDirection',
    'Schedule',
    'ScheduleResult',
    'Trigger',
    'TriggerResult',
    'TriggerMethod',
    'Team',
    'TeamMember',
    'TeamResult',
    'TeamRole',
]
