# agent/finance/openclaw_skill.py
"""
OpenClaw Skill Adapter — exposes NeoMind finance as an installable OpenClaw skill.

When OpenClaw dispatches a command like "/stock AAPL" from WhatsApp/Telegram/Slack,
this adapter routes it to the appropriate finance component and returns a formatted reply.

Also handles:
- Auto-triggering on financial keywords in natural conversation
- Formatting responses for mobile messaging (compact, markdown-friendly)
- Dashboard generation and attachment for /digest commands
- Alert registration from messaging platforms

Skill SKILL.md metadata is generated by `export_skill_metadata()`.
"""

import asyncio
import re
import json
from datetime import datetime, timezone
from typing import Dict, List, Optional, Any, Tuple

from .openclaw_gateway import OpenClawGateway, IncomingMessage


# ── Financial keyword triggers (same as fin.yaml auto_search_triggers) ──

FINANCE_TRIGGERS_EN = {
    "stock", "price", "market", "earnings", "revenue", "dividend",
    "crypto", "bitcoin", "btc", "eth", "portfolio", "invest",
    "fed", "inflation", "gdp", "rate", "bond", "yield",
    "ipo", "merger", "acquisition",
}

FINANCE_TRIGGERS_ZH = {
    "股票", "股价", "行情", "财报", "营收", "分红",
    "加密", "比特币", "以太坊", "投资组合",
    "央行", "利率", "通胀", "降息", "加息",
}


class OpenClawFinanceSkill:
    """
    Routes OpenClaw messages to NeoMind finance components.

    Architecture:
        OpenClaw Gateway → IncomingMessage → this adapter → finance components → reply text
    """

    def __init__(self, components: Dict[str, Any], gateway: Optional[OpenClawGateway] = None):
        """
        Args:
            components: Dict from get_finance_components() — search, data_hub, memory, etc.
            gateway: Optional OpenClawGateway instance. If provided, auto-registers handlers.
        """
        self.components = components
        self.gateway = gateway
        self._search = components.get("search")
        self._data_hub = components.get("data_hub")
        self._memory = components.get("memory")
        self._digest = components.get("digest")
        self._quant = components.get("quant")
        self._diagram = components.get("diagram")
        self._dashboard = components.get("dashboard")

        # Map command names to handler methods
        self._command_handlers = {
            "stock": self._handle_stock,
            "crypto": self._handle_crypto,
            "news": self._handle_news,
            "digest": self._handle_digest,
            "compute": self._handle_compute,
            "portfolio": self._handle_portfolio,
            "predict": self._handle_predict,
            "alert": self._handle_alert,
            "compare": self._handle_compare,
            "watchlist": self._handle_watchlist,
            "risk": self._handle_risk,
            "sources": self._handle_sources,
            "calendar": self._handle_calendar,
            "chart": self._handle_chart,
            "memory": self._handle_memory,
            "sync": self._handle_sync,
        }

        # Register with gateway if provided
        if gateway:
            gateway.on_message(self.handle_incoming)

    async def handle_incoming(self, msg: IncomingMessage) -> Optional[str]:
        """Main entry point for incoming messages from OpenClaw.

        Routes messages to the appropriate handler based on:
        1. Explicit /command syntax
        2. Financial keyword detection in natural language

        Returns reply text or None (if message isn't finance-related).
        """
        text = msg.text.strip()

        # Check for explicit slash commands
        if text.startswith("/"):
            cmd, args = self._parse_command(text)
            handler = self._command_handlers.get(cmd)
            if handler:
                try:
                    return await handler(args, msg)
                except Exception as e:
                    return f"⚠️ Error: {e}"
            return None  # Not our command — let other skills handle it

        # Check for financial keyword triggers (auto-detect finance queries)
        if self._is_finance_query(text):
            return await self._handle_natural_query(text, msg)

        return None  # Not finance-related

    # ── Command Parsing ──────────────────────────────────────────────

    @staticmethod
    def _parse_command(text: str) -> Tuple[str, str]:
        """Parse '/command args' into (command, args)."""
        parts = text[1:].split(maxsplit=1)
        cmd = parts[0].lower() if parts else ""
        args = parts[1].strip() if len(parts) > 1 else ""
        return cmd, args

    @staticmethod
    def _is_finance_query(text: str) -> bool:
        """Detect if a natural language message is finance-related."""
        text_lower = text.lower()
        for trigger in FINANCE_TRIGGERS_EN:
            if trigger in text_lower:
                return True
        for trigger in FINANCE_TRIGGERS_ZH:
            if trigger in text:
                return True
        # Check for ticker patterns ($AAPL, $BTC)
        if re.search(r'\$[A-Z]{1,5}\b', text):
            return True
        return False

    # ── Command Handlers ─────────────────────────────────────────────

    async def _handle_stock(self, args: str, msg: IncomingMessage) -> str:
        """Look up stock price and fundamentals."""
        if not args:
            return "Usage: /stock AAPL\nLook up stock price, fundamentals, and analysis."

        symbol = args.upper().split()[0]
        if not self._data_hub:
            return "⚠️ Data hub not available."

        try:
            data = await self._data_hub.get_stock_price(symbol)
            if data:
                price = data.get("price", "?")
                change = data.get("change", 0)
                change_pct = data.get("change_pct", 0)
                sign = "+" if change >= 0 else ""
                icon = "📈" if change >= 0 else "📉"
                source = data.get("source", "")
                return (
                    f"{icon} **{symbol}** ${price}\n"
                    f"Change: {sign}{change} ({sign}{change_pct}%)\n"
                    f"Source: {source} · {datetime.now().strftime('%H:%M UTC')}"
                )
            return f"No data found for {symbol}."
        except Exception as e:
            return f"⚠️ Lookup failed: {e}"

    async def _handle_crypto(self, args: str, msg: IncomingMessage) -> str:
        """Look up crypto price."""
        if not args:
            return "Usage: /crypto BTC\nCryptocurrency price, market cap, and trends."

        symbol = args.upper().split()[0]
        if not self._data_hub:
            return "⚠️ Data hub not available."

        try:
            data = await self._data_hub.get_crypto_price(symbol)
            if data:
                price = data.get("price", "?")
                change_24h = data.get("change_24h", 0)
                sign = "+" if change_24h >= 0 else ""
                return (
                    f"{'📈' if change_24h >= 0 else '📉'} **{symbol}** ${price:,.2f}\n"
                    f"24h: {sign}{change_24h:.2f}%\n"
                    f"Source: {data.get('source', '')} · {datetime.now().strftime('%H:%M UTC')}"
                )
            return f"No data found for {symbol}."
        except Exception as e:
            return f"⚠️ Lookup failed: {e}"

    async def _handle_news(self, args: str, msg: IncomingMessage) -> str:
        """Multi-source financial news search."""
        query = args or "financial news today"
        if not self._search:
            return "⚠️ Search engine not available."

        try:
            result = await self._search.search(query, max_results=5)
            if not result.items:
                return f"No news found for: {query}"

            lines = [f"📰 **News: {query}**", f"Sources: {len(result.sources_used)} | Queries: {len(result.expanded_queries)}"]
            for i, item in enumerate(result.items[:5], 1):
                lang = " 🇨🇳" if item.language == "zh" else ""
                lines.append(f"{i}. [{item.title}]({item.url}){lang}")
                if item.snippet:
                    lines.append(f"   _{item.snippet[:80]}_")
            return "\n".join(lines)
        except Exception as e:
            return f"⚠️ Search failed: {e}"

    async def _handle_digest(self, args: str, msg: IncomingMessage) -> str:
        """Generate daily market digest."""
        if not self._digest:
            return "⚠️ Digest engine not available."

        try:
            digest = await self._digest.generate_digest()
            lines = [
                f"📊 **Market Digest** — {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
                f"Sources: {digest.sources_used} | EN: {digest.en_count} | ZH: {digest.zh_count}",
                "",
            ]

            # Top 5 items
            for item in digest.items[:5]:
                icon = "🔴" if item.impact_score >= 5 else ("🟡" if item.impact_score >= 3 else "🟢")
                lines.append(f"{icon} {item.title}")
                if item.source:
                    lines.append(f"   _{item.source}_")

            # Conflicts
            if digest.conflicts:
                lines.append(f"\n⚡ **{len(digest.conflicts)} conflicts detected**")
                for c in digest.conflicts[:2]:
                    lines.append(f"  • {c.entity}: {c.severity}")

            # If dashboard is available, generate HTML
            if self._dashboard and self.gateway:
                try:
                    self._dashboard.reset()
                    self._dashboard.set_title("Market Digest")
                    news_data = [
                        {"title": item.title, "source": item.source,
                         "impact": item.impact_magnitude, "language": item.language}
                        for item in digest.items[:15]
                    ]
                    self._dashboard.add_news_section(news_data)
                    html = self._dashboard.render()
                    await self.gateway.push_digest(
                        html, "\n".join(lines[:6]), None
                    )
                    lines.append("\n📎 _Full dashboard attached_")
                except Exception:
                    pass

            return "\n".join(lines)
        except Exception as e:
            return f"⚠️ Digest generation failed: {e}"

    async def _handle_compute(self, args: str, msg: IncomingMessage) -> str:
        """Run financial math."""
        if not args:
            return (
                "Usage: /compute <expression>\n"
                "Examples:\n"
                "  /compute compound 10000 0.08 10\n"
                "  /compute sharpe 0.12 0.04 0.15\n"
                "  /compute var 100000 0.02 1.65"
            )
        if not self._quant:
            return "⚠️ Quant engine not available."

        parts = args.split()
        func = parts[0].lower()

        try:
            if func == "compound" and len(parts) >= 4:
                result = self._quant.compound_return(
                    float(parts[1]), float(parts[2]), float(parts[3])
                )
                return f"📐 **Compound Return**\n{result}"
            elif func == "sharpe" and len(parts) >= 4:
                result = self._quant.sharpe_ratio(
                    float(parts[1]), float(parts[2]), float(parts[3])
                )
                return f"📐 **Sharpe Ratio**\n{result}"
            elif func == "var" and len(parts) >= 4:
                result = self._quant.value_at_risk(
                    float(parts[1]), float(parts[2]), float(parts[3])
                )
                return f"📐 **Value at Risk**\n{result}"
            else:
                return f"Unknown compute function: {func}. Try: compound, sharpe, var"
        except Exception as e:
            return f"⚠️ Computation error: {e}"

    async def _handle_portfolio(self, args: str, msg: IncomingMessage) -> str:
        """View portfolio."""
        if not self._memory:
            return "⚠️ Memory not available."
        return "📁 Portfolio view — coming in Phase 3.\nUse /watchlist to manage tracked assets."

    async def _handle_predict(self, args: str, msg: IncomingMessage) -> str:
        """Log a prediction."""
        if not args:
            return "Usage: /predict AAPL bullish 0.75 \"AI revenue will drive 20% growth\""

        parts = args.split(maxsplit=3)
        if len(parts) < 3:
            return "Need: /predict <symbol> <bullish|bearish> <confidence> [rationale]"

        symbol = parts[0].upper()
        direction = parts[1].lower()
        try:
            confidence = float(parts[2])
        except ValueError:
            return "Confidence must be a number (0.0 to 1.0)"

        rationale = parts[3] if len(parts) > 3 else ""

        if self._memory:
            try:
                self._memory.store_prediction(
                    symbol=symbol,
                    direction=direction,
                    confidence=confidence,
                    rationale=rationale,
                )
            except Exception:
                pass

        icon = "📈" if direction == "bullish" else "📉"
        return f"{icon} Prediction logged: **{symbol}** {direction} ({confidence:.0%})\n{rationale}"

    async def _handle_alert(self, args: str, msg: IncomingMessage) -> str:
        """Set price alert."""
        if not args:
            return "Usage: /alert AAPL above 200\nSet a price alert for a symbol."
        return f"🔔 Alert feature — coming in Phase 4.\nWill push via {msg.channel} when triggered."

    async def _handle_compare(self, args: str, msg: IncomingMessage) -> str:
        """Compare assets."""
        if not args:
            return "Usage: /compare AAPL MSFT\nCompare two or more assets."
        return "📊 Compare feature — coming in Phase 3."

    async def _handle_watchlist(self, args: str, msg: IncomingMessage) -> str:
        """Manage watchlist."""
        if not args:
            return "Usage: /watchlist [add|remove] <symbol>\n  /watchlist — show current list"
        return "👁 Watchlist management — coming in Phase 3."

    async def _handle_risk(self, args: str, msg: IncomingMessage) -> str:
        """Risk assessment."""
        if not args:
            return "Usage: /risk AAPL\nAssess portfolio risk metrics."
        return "⚖️ Risk assessment — coming in Phase 4."

    async def _handle_sources(self, args: str, msg: IncomingMessage) -> str:
        """View source trust scores."""
        from agent.services.source_registry import SourceTrustTracker
        tracker = SourceTrustTracker()
        return tracker.format_report()

    async def _handle_calendar(self, args: str, msg: IncomingMessage) -> str:
        """Financial events calendar."""
        return "📅 Calendar feature — coming in Phase 4."

    async def _handle_chart(self, args: str, msg: IncomingMessage) -> str:
        """Generate chart."""
        if not self._diagram:
            return "⚠️ Diagram generator not available."
        return "📊 Chart generation via messaging — use /digest for full dashboard."

    async def _handle_memory(self, args: str, msg: IncomingMessage) -> str:
        """Query secure memory."""
        if not self._memory:
            return "⚠️ Memory not available."
        return "🧠 Memory query — coming in Phase 3."

    async def _handle_sync(self, args: str, msg: IncomingMessage) -> str:
        """Sync status."""
        if self.gateway:
            return self.gateway.get_status()
        return "⚠️ Gateway not connected."

    # ── Natural Language Query Handler ───────────────────────────────

    async def _handle_natural_query(self, text: str, msg: IncomingMessage) -> Optional[str]:
        """Handle finance-related natural language (not a slash command).

        Routes to search or data lookup based on content.
        """
        # Check for ticker mentions ($AAPL, $BTC)
        tickers = re.findall(r'\$([A-Z]{1,5})\b', text)
        if tickers and self._data_hub:
            results = []
            for ticker in tickers[:3]:
                try:
                    data = await self._data_hub.get_stock_price(ticker)
                    if data:
                        price = data.get("price", "?")
                        change = data.get("change", 0)
                        sign = "+" if change >= 0 else ""
                        results.append(f"**{ticker}** ${price} ({sign}{change})")
                except Exception:
                    pass
            if results:
                return "📊 " + " | ".join(results)

        # Fall back to search
        if self._search:
            try:
                result = await self._search.search(text, max_results=3)
                if result.items:
                    lines = ["📰 _Related news:_"]
                    for item in result.items[:3]:
                        lines.append(f"• [{item.title}]({item.url})")
                    return "\n".join(lines)
            except Exception:
                pass

        return None  # Couldn't handle it


# ── Skill Metadata Export ────────────────────────────────────────────

def export_skill_metadata() -> str:
    """Generate SKILL.md content for OpenClaw skill packaging.

    This is the metadata file that OpenClaw reads when installing the skill.
    """
    return """---
name: neomind-finance
version: 1.0.0
description: Personal Finance & Investment Intelligence — multi-source news, quantified analysis, encrypted memory, prediction tracking
author: NeoMind
license: MIT
triggers:
  - stock
  - crypto
  - bitcoin
  - price
  - market
  - earnings
  - portfolio
  - invest
  - fed
  - inflation
  - 股票
  - 加密
  - 央行
capabilities:
  - finance
  - news
  - crypto
  - analysis
  - alerts
  - computation
dependencies:
  python: ">=3.8"
  packages:
    - feedparser>=6.0.0
    - requests>=2.31.0
    - cryptography>=41.0.0
---

# NeoMind Finance Skill

Personal Finance & Investment Intelligence for OpenClaw.

## Commands

| Command | Description | Example |
|---------|-------------|---------|
| /stock | Stock price and analysis | /stock AAPL |
| /crypto | Cryptocurrency price | /crypto BTC |
| /news | Multi-source news search (EN + ZH) | /news Fed rate |
| /digest | Daily market digest with dashboard | /digest |
| /compute | Financial math | /compute compound 10000 0.08 10 |
| /portfolio | Portfolio overview | /portfolio |
| /predict | Log a prediction | /predict TSLA bullish 0.7 |
| /alert | Set price alert | /alert BTC above 70000 |
| /compare | Compare assets | /compare AAPL MSFT |
| /watchlist | Manage watchlist | /watchlist add NVDA |
| /risk | Risk assessment | /risk |
| /sources | Source trust scores | /sources |
| /calendar | Financial events | /calendar |
| /chart | Generate chart | /chart pie |
| /memory | Query memory | /memory AAPL |
| /sync | Sync status | /sync |

## Data Sources

**Tier 1 (Free):** DuckDuckGo, Google News RSS, 20+ RSS feeds (EN + ZH)
**Tier 2 (Optional):** Tavily, Serper, NewsAPI.org
**Market Data:** Finnhub, yfinance, AKShare, CoinGecko

## Features

- Hybrid search with Reciprocal Rank Fusion across 5+ sources
- TF-IDF fuzzy matching with financial stemming
- Query expansion (EN↔ZH cross-language)
- Content extraction via trafilatura
- Encrypted local memory (AES-128 Fernet)
- Source trust tracking with Bayesian updates
- Conflict detection between sources
- Prediction tracking with accuracy history
- HTML dashboard generation (Chart.js)
- First-principles financial reasoning
"""
